export const addEventFormElements = [
  {
    label: "Event Title",
    name: "title",
    componentType: "input",
    type: "text",
    placeholder: "Enter event title",
  },
  {
    label: "Description",
    name: "description",
    componentType: "textarea",
    placeholder: "Enter event description",
  },
  {
    label: "Event Type",
    name: "eventType",
    componentType: "select",
    options: [
      { id: "conference", label: "Conference" },
      { id: "workshop", label: "Workshop" },
      { id: "seminar", label: "Seminar" },
      { id: "reunion", label: "Reunion" },
      { id: "webinar", label: "Webinar" },
      { id: "networking", label: "Networking" },
      { id: "cultural", label: "Cultural" },
      { id: "sports", label: "Sports" },
      { id: "other", label: "Other" },
    ],
  },
  {
    label: "Start Date & Time",
    name: "startDateTime",
    componentType: "input",
    type: "datetime-local",
    placeholder: "",
  },
  {
    label: "End Date & Time",
    name: "endDateTime",
    componentType: "input",
    type: "datetime-local",
    placeholder: "",
  },
  {
    label: "Registration Fee (₹)",
    name: "registrationFee",
    componentType: "input",
    type: "number",
    placeholder: "0",
  },
  {
    label: "Max Attendees",
    name: "maxAttendees",
    componentType: "input",
    type: "number",
    placeholder: "Leave empty for unlimited",
  },
  {
    label: "Venue Name",
    name: "venueName",
    componentType: "input",
    type: "text",
    placeholder: "Enter venue name",
  },
  {
    label: "City",
    name: "venueCity",
    componentType: "input",
    type: "text",
    placeholder: "Enter city",
  },
  {
    label: "Venue Address",
    name: "venueAddress",
    componentType: "input",
    type: "text",
    placeholder: "Enter venue address",
  },
  {
    label: "State",
    name: "venueState",
    componentType: "input",
    type: "text",
    placeholder: "Enter state",
  },
  {
    label: "Country",
    name: "venueCountry",
    componentType: "input",
    type: "text",
    placeholder: "India",
  },
  {
    label: "Pincode",
    name: "venuePincode",
    componentType: "input",
    type: "text",
    placeholder: "Enter pincode",
  },
  {
    label: "Meeting Link",
    name: "meetingLink",
    componentType: "input",
    type: "url",
    placeholder: "https://meet.google.com/...",
  },
];

export const eventTypeSpecificFields = {
  conference: ["maxAttendees", "registrationFee", "venueName", "venueCity", "venueAddress"],
  workshop: ["maxAttendees", "registrationFee", "venueName", "venueCity"],
  seminar: ["registrationFee", "venueName", "venueCity"],
  reunion: ["venueName", "venueCity", "venueAddress", "venueState", "venuePincode"],
  webinar: ["meetingLink", "maxAttendees"],
  networking: ["maxAttendees", "venueName", "venueCity"],
  cultural: ["venueName", "venueCity", "registrationFee"],
  sports: ["venueName", "venueCity", "maxAttendees"],
  other: [],
};